//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_admin
    {
        public int id { get; set; }
        public string admin_name { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string email { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string password { get; set; }
    }
}
