//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_cart
    {
        public int cart_id { get; set; }
        public Nullable<int> id { get; set; }
        public string pet_name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual tb_pet tb_pet { get; set; }
    }
}
