//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pet()
        {
            this.tb_buy = new HashSet<tb_buy>();
            this.tb_cart = new HashSet<tb_cart>();
        }
        public int id { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string pet_name { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string species { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string breed { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_buy> tb_buy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cart> tb_cart { get; set; }
    }
}
